# Generated by Django 5.2 on 2025-04-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('ts', models.DateTimeField()),
            ],
            options={
                'db_table': 'api',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aqi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('pmlevel', models.FloatField()),
                ('ts', models.DateTimeField()),
            ],
            options={
                'db_table': 'aqi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kidbright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('lux', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kidbright',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pm2_5', models.FloatField()),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ts', models.DateTimeField()),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=16, null=True)),
                ('temperature_2m_c_field', models.DecimalField(blank=True, db_column='temperature_2m (°C)', decimal_places=1, max_digits=3, null=True)),
                ('wind_speed_10m_km_h_field', models.DecimalField(blank=True, db_column='wind_speed_10m (km/h)', decimal_places=1, max_digits=3, null=True)),
                ('wind_speed_80m_km_h_field', models.DecimalField(blank=True, db_column='wind_speed_80m (km/h)', decimal_places=1, max_digits=3, null=True)),
                ('wind_direction_10m_field', models.IntegerField(blank=True, db_column='wind_direction_10m (°)', null=True)),
                ('wind_direction_80m_field', models.IntegerField(blank=True, db_column='wind_direction_80m (°)', null=True)),
                ('relative_humidity_2m_field', models.IntegerField(blank=True, db_column='relative_humidity_2m (%)', null=True)),
            ],
            options={
                'db_table': 'second',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('ts', models.DateTimeField()),
            ],
            options={
                'db_table': 'tmd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('sensor', models.CharField(max_length=11)),
                ('source', models.CharField(max_length=9)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'weather',
                'managed': False,
            },
        ),
    ]
